---
- hosts: localhost
  tasks:
   - name: install git!!!
     yum: name=git state=latest
     become: yes
     become_method: sudo
   - name: clone petClinic repo from git
     git: repo=https://github.com/ysegalgit/spring-petclinic.git dest=~/petclinict clone=yes
   - name: clone devOpsCourseRepo repo from git
     git: repo=https://github.com/ysegalgit/devOpsCourseRepo.git dest=~/devOpsCourseRepo clone=yes update=no
   - name: create maven directory
     file:  path=~/maven state=directory mode=0755
   - name: install maven
     unarchive: src=http://apache.spd.co.il/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip dest=~/maven copy=no creates=~/maven/apache-maven-3.3.9/README.txt
   - name: set env m2_home
     lineinfile: dest=/home/ec2-user/.bash_profile regexp="^M2_HOME.*" line="M2_HOME=/home/ec2-user/maven/apache-maven-3.3.9" insertbefore="^PATH="
   - name: export M2_HOME
     lineinfile: dest=/home/ec2-user/.bash_profile insertafter="^M2_HOME=" line="export M2_HOME"
   - name: set M2
     lineinfile: dest=/home/ec2-user/.bash_profile insertafter="^M2_HOME=" line="M2=$M2_HOME/bin"
   - name: export M2
     lineinfile: dest=/home/ec2-user/.bash_profile insertafter="^M2=" line="export M2"
   - name: Add M2 to PATH
     lineinfile: dest=/home/ec2-user/.bash_profile regexp="^PATH=.*:$M2" insertafter="^PATH=" line="PATH=$PATH:$M2"
